# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker

trigger:
- master

pr:
  autoCancel: true
  # PRs into ...
  branches:
    include:
    - master

schedules:
- cron: "0 0 * * *"
  displayName: 'daily build'
  branches:
    include:
      - master
  always: true


jobs:

- job: 'Docker'
  strategy:
    matrix:
      ROS-noetic:
        dockerfile: 'Dockerfile.rosnoetic'
        imageName: 'ubuntu-latest'
      ROS-iron:
        dockerfile: 'Dockerfile.ros-iron'
        imageName: 'ubuntu-latest'
  pool:
    vmImage: $(imageName)
  steps:
    # Currently only for testing, so no tagging needed.
    - script: docker build . --file $(dockerfile) || exit 1
      displayName: 'docker build'


- job: 'Test'
  strategy:
    matrix:
      Python-3.8-ubuntu:
        python.version: '3.8'
        imageName: 'ubuntu-latest'
      Python-3.11-ubuntu:
        python.version: '3.11'
        imageName: 'ubuntu-latest'
      Python-3.11-mac:
        python.version: '3.11'
        imageName: 'macOS-latest'
      Python-3.11-windows:
        python.version: '3.11'
        imageName: 'windows-latest'
    maxParallel: 10
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install . --no-binary evo
      evo_config show --brief --no_color
    displayName: 'Install and configure package and dependencies'

  - script: |
      pip install mypy types-PyYAML
      mypy --ignore-missing-imports evo/ test/ contrib/ doc/ --exclude test/tum_benchmark_tools/
    displayName: 'mypy'

  - script: |
      pip install pytest
      pytest -sv --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()


- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: |
      pip install --upgrade setuptools
      python setup.py sdist
    displayName: 'Build sdist'

# Currently, that's it. No actual deployment.
